# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelPackages = pkgs.linuxPackages_zen;
  boot.kernelModules = [ "kvm-amd" "msr" ];
  boot.kernelParams = [ "quiet" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/53a7012a-1184-4a98-ac77-22016be9758a";
      fsType = "ext4";
      options = [ "discard" "noatime" "lazytime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C2A6-1B05";
      fsType = "vfat";
      options = [ "discard" "noatime" "lazytime" ];
    };

  fileSystems."/mnt/Data" =
    { device = "/dev/disk/by-uuid/ea47dc08-bef2-4be6-87d7-3a8f7eb046ab";
      fsType = "ext4";
      options = [ "relatime" ];
    };

  fileSystems."/mnt/Videos" =
    { device = "/dev/disk/by-uuid/da808821-e073-4610-8a62-48a7332bbb92";
      fsType = "ext4";
      options = [ "relatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/776264a5-6d43-42ef-b18f-79269054ac74"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
