# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelPackages = pkgs.linuxPackages_zen;
  boot.kernelModules = [ "kvm-intel" "msr" ];
  boot.kernelParams = [ "i915.enable_psr=0" "i915.enable_fbc=0" "quiet" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/364f3de2-8ad0-4697-8989-f44c866c88ea";
      fsType = "ext4";
      options = [ "discard" "noatime" "lazytime" ];
    };

  boot.initrd.luks.devices."luks-833d73d6-b3c0-46ae-87e8-18d7dc2dc50b".device = "/dev/disk/by-uuid/833d73d6-b3c0-46ae-87e8-18d7dc2dc50b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C07A-2767";
      fsType = "vfat";
      options = [ "discard" "noatime" "lazytime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/33e06e4d-14eb-4a1b-9680-c9f3ccd6c076"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
